site_name: ergoCub Software
site_url: https://mesh-iit.github.io/ergocub-software/
site_description: All the software running on ergoCub
site_author: iCub-Tech
copyright: BSD 3-Clause License

repo_name: mesh-iit/ergocub-software
repo_url: https://github.com/mesh-iit/ergocub-software/
edit_uri: 'edit/master/doc/mkdocs/docs'
docs_dir: 'doc/mkdocs/docs'

theme:
  name: material
  favicon: assets/head-solid.png  # PNG for browser tab
  icon:
    logo: material/robot          # Vector icon for header/nav
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: lucide/sun-moon
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: lucide/sun
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: lucide/moon-star
        name: Switch to system preference

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.magiclink:
      user: mesh-iit
      repo: ergocub-software
      repo_url_shortener: true
      repo_url_shorthand: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

plugins:
  - search
  - autorefs:
      resolve_closest: true



nav:
    - Home: 'index.md'
    - Quickstart Guide: 'quickstart_guide.md'
    - Documentation: https://mesh-iit.github.io/ergocub-software/doc/doxygen/doc/html/index.html
    - Modules:
        - Getting started: 'modules_intro.md'
        - ergoCubEmotions: 'ergocubemotions.md'
    - CHANGELOG: 'CHANGELOG.md'
